"""add expense date column

Revision ID: 1f5b4290f038
Revises: 3cf1ca0dc38e
Create Date: 2026-07-31 13:13:42.156771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import date

# revision identifiers, used by Alembic.
revision: str = '1f5b4290f038'
down_revision: Union[str, Sequence[str], None] = '3cf1ca0dc38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenses",
        sa.Column("date", sa.Date(), nullable=True)
    )
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
